### ISSUE TITLE
Longpath is broken after the 0.6.0 release

### ISSUE THREAD

**Issue by GuyIncognito1986** [cake-contrib/Cake.LongPath.Module#15] opened 2019-04-26 14:50 UTC
Repro:

Run a cake script with longpath loaded. Will always return "invalid directory". (At least on windows.)

**Comment by GuyIncognito1986** [comment] 2019-04-26 14:50
Downgrading to 0.5.0 solves this issue.

**Comment by devlead** [comment] 2019-05-03 21:18
Long path module will only work on WIndows.

Version 0.6.0 targets Cake 0.33.0 which version of Cake are you using?

Do you have an example of the script you're using? How hare you bootstrapping the installation of the module?

Integration tests are passing on CI on WIndows Server 2016
https://ci.appveyor.com/project/cakecontrib/cake-longpath-module/builds/24294667#L442

And I've tested the module example locally on WIndows 10 without issue
https://github.com/cake-contrib/Cake.LongPath.Module/blob/develop/moduleusageexample/build.cake

Not yet been able to reproduce the issue yet.

**Comment by devlead** [comment] 2019-05-03 21:33
More context in cake-build/cake#2542

Might be os related, and new version of Pri.LongPath, I'll need to add more integration tests.

**Comment by justin-caldicott** [comment] 2019-07-18 21:23
Same problem running on Windows 10.  Downgrade to 0.5.0 sorted it.

**Comment by azchohfi** [comment] 2019-10-04 00:48
The problem is the new version of the Pri.LongPath:
https://github.com/cake-contrib/Cake.LongPath.Module/blob/c7cfb4cdbbe6e9cb099a4ac0d9bde2158917d66a/src/Cake.LongPath.Module/Cake.LongPath.Module.csproj#L40-L42
If you downgrade from 2.0.47 to 2.0.45, it works again.
I've opened an issue on their side (https://github.com/peteraritchie/LongPath/issues/82) but it's very simple to just wrap the LongPathDirectory.Exist on a try catch for now and return false if it throws anything. I'll send a PR to unblock on our side, since we don't know when that's going to be fixed on Pri.LongPath.

**Comment by azchohfi** [comment] 2019-10-04 00:54
The only difference from those versions is their dependency change, so it's actually simpler if I just downgrade our dependency.

**Comment by devlead** [comment] 2019-10-26 08:23
Fixed by #17

**Closed by devlead** 2019-10-26 08:23 UTC
